/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISettlementFactory,
  ISettlementFactoryInterface,
} from "../../../../contracts/assets/settlements/ISettlementFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "worldAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "assetName",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "ownerTokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "zoneAddress",
        type: "address",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISettlementFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ISettlementFactoryInterface {
    return new utils.Interface(_abi) as ISettlementFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISettlementFactory {
    return new Contract(address, _abi, signerOrProvider) as ISettlementFactory;
  }
}
