/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assets from "./assets";
export type { assets };
import type * as flags from "./flags";
export type { flags };
import type * as libraries from "./libraries";
export type { libraries };
import type * as periphery from "./periphery";
export type { periphery };
import type * as token from "./token";
export type { token };
