/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBattleInterface extends ethers.utils.Interface {
  functions: {
    "isOnSideA(address)": FunctionFragment;
    "timing()": FunctionFragment;
    "getSideA()": FunctionFragment;
    "getSideB()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isOnSideA", values: [string]): string;
  encodeFunctionData(functionFragment: "timing", values?: undefined): string;
  encodeFunctionData(functionFragment: "getSideA", values?: undefined): string;
  encodeFunctionData(functionFragment: "getSideB", values?: undefined): string;

  decodeFunctionResult(functionFragment: "isOnSideA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSideA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSideB", data: BytesLike): Result;

  events: {};
}

export class IBattle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBattleInterface;

  functions: {
    isOnSideA(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    timing(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber] & {
          creationTime: BigNumber;
          finishTime: BigNumber;
        }
      ]
    >;

    getSideA(overrides?: CallOverrides): Promise<[string[]]>;

    getSideB(overrides?: CallOverrides): Promise<[string[]]>;
  };

  isOnSideA(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  timing(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { creationTime: BigNumber; finishTime: BigNumber }
  >;

  getSideA(overrides?: CallOverrides): Promise<string[]>;

  getSideB(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    isOnSideA(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    timing(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        creationTime: BigNumber;
        finishTime: BigNumber;
      }
    >;

    getSideA(overrides?: CallOverrides): Promise<string[]>;

    getSideB(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    isOnSideA(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    timing(overrides?: CallOverrides): Promise<BigNumber>;

    getSideA(overrides?: CallOverrides): Promise<BigNumber>;

    getSideB(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isOnSideA(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    timing(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSideA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSideB(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
