/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistry__factory } from "./IRegistry__factory";
export { IWorld__factory } from "./IWorld__factory";
export { Registry__factory } from "./Registry__factory";
export { World__factory } from "./World__factory";
