/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBuildingFactory,
  IBuildingFactoryInterface,
} from "../../../../contracts/assets/buildings/IBuildingFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "worldAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "assetName",
        type: "string",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBuildingFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IBuildingFactoryInterface {
    return new utils.Interface(_abi) as IBuildingFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBuildingFactory {
    return new Contract(address, _abi, signerOrProvider) as IBuildingFactory;
  }
}
