/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export declare namespace IBattle {
  export type CasualtyStruct = {
    unitSpec: BigNumberish;
    casualties: BigNumberish;
  };

  export type CasualtyStructOutput = [BigNumber, BigNumber] & {
    unitSpec: BigNumber;
    casualties: BigNumber;
  };
}

export interface BattleInterface extends utils.Interface {
  functions: {
    "_calculateAllCasualties()": FunctionFragment;
    "_calculateStage1CasualtiesForDron()": FunctionFragment;
    "assetName()": FunctionFragment;
    "assetType()": FunctionFragment;
    "calculateTimings(uint256,uint256,uint256,bool,uint256,uint256)": FunctionFragment;
    "calculateUserCasualties(address)": FunctionFragment;
    "canExitFromBattle()": FunctionFragment;
    "casualties(bool,string)": FunctionFragment;
    "checkCasualties(bool,string,uint256)": FunctionFragment;
    "exitBattle()": FunctionFragment;
    "getLobbyDuration(bool)": FunctionFragment;
    "getOngoingDuration(bool)": FunctionFragment;
    "getSideALength()": FunctionFragment;
    "getSideBLength()": FunctionFragment;
    "initBattle(address,address)": FunctionFragment;
    "isJoinTime()": FunctionFragment;
    "isOnSideA(address)": FunctionFragment;
    "joinBattle(bool)": FunctionFragment;
    "offchainCaller()": FunctionFragment;
    "position()": FunctionFragment;
    "sideA(uint256)": FunctionFragment;
    "sideB(uint256)": FunctionFragment;
    "sideUnitsCount(bool,string)": FunctionFragment;
    "startBattle()": FunctionFragment;
    "timing()": FunctionFragment;
    "userUnitsCount(address,string)": FunctionFragment;
    "world()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_calculateAllCasualties"
      | "_calculateStage1CasualtiesForDron"
      | "assetName"
      | "assetType"
      | "calculateTimings"
      | "calculateUserCasualties"
      | "canExitFromBattle"
      | "casualties"
      | "checkCasualties"
      | "exitBattle"
      | "getLobbyDuration"
      | "getOngoingDuration"
      | "getSideALength"
      | "getSideBLength"
      | "initBattle"
      | "isJoinTime"
      | "isOnSideA"
      | "joinBattle"
      | "offchainCaller"
      | "position"
      | "sideA"
      | "sideB"
      | "sideUnitsCount"
      | "startBattle"
      | "timing"
      | "userUnitsCount"
      | "world"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_calculateAllCasualties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateStage1CasualtiesForDron",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assetName", values?: undefined): string;
  encodeFunctionData(functionFragment: "assetType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateTimings",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUserCasualties",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "canExitFromBattle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "casualties",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkCasualties",
    values: [boolean, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exitBattle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLobbyDuration",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getOngoingDuration",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getSideALength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSideBLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initBattle",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isJoinTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOnSideA", values: [string]): string;
  encodeFunctionData(functionFragment: "joinBattle", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "offchainCaller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "position", values?: undefined): string;
  encodeFunctionData(functionFragment: "sideA", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "sideB", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "sideUnitsCount",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "startBattle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timing", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userUnitsCount",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "world", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_calculateAllCasualties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateStage1CasualtiesForDron",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateTimings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUserCasualties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canExitFromBattle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "casualties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkCasualties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exitBattle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLobbyDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOngoingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSideALength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSideBLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initBattle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isJoinTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOnSideA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinBattle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offchainCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "position", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sideA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sideB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sideUnitsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startBattle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userUnitsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "world", data: BytesLike): Result;

  events: {
    "CasualtiesAdded(bool,uint256,uint256)": EventFragment;
    "Finished(uint256,uint256[],uint256[])": EventFragment;
    "Initialized(uint8)": EventFragment;
    "Joined(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CasualtiesAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Finished"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Joined"): EventFragment;
}

export interface CasualtiesAddedEventObject {
  isSideA: boolean;
  unitSpec: BigNumber;
  casualities: BigNumber;
}
export type CasualtiesAddedEvent = TypedEvent<
  [boolean, BigNumber, BigNumber],
  CasualtiesAddedEventObject
>;

export type CasualtiesAddedEventFilter = TypedEventFilter<CasualtiesAddedEvent>;

export interface FinishedEventObject {
  finishTime: BigNumber;
  casualitiesA: BigNumber[];
  casualitiesB: BigNumber[];
}
export type FinishedEvent = TypedEvent<
  [BigNumber, BigNumber[], BigNumber[]],
  FinishedEventObject
>;

export type FinishedEventFilter = TypedEventFilter<FinishedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface JoinedEventObject {
  armyAddress: string;
  isSideA: boolean;
}
export type JoinedEvent = TypedEvent<[string, boolean], JoinedEventObject>;

export type JoinedEventFilter = TypedEventFilter<JoinedEvent>;

export interface Battle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BattleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _calculateAllCasualties(
      overrides?: CallOverrides
    ): Promise<
      [
        IBattle.CasualtyStructOutput[],
        IBattle.CasualtyStructOutput[],
        BigNumber
      ]
    >;

    _calculateStage1CasualtiesForDron(
      overrides?: CallOverrides
    ): Promise<
      [
        IBattle.CasualtyStructOutput[],
        IBattle.CasualtyStructOutput[],
        BigNumber
      ] & {
        _sideACasualties: IBattle.CasualtyStructOutput[];
        _sideBCasualties: IBattle.CasualtyStructOutput[];
        length: BigNumber;
      }
    >;

    assetName(overrides?: CallOverrides): Promise<[string]>;

    assetType(overrides?: CallOverrides): Promise<[string]>;

    calculateTimings(
      globalMultiplier: BigNumberish,
      baseLobbyDuration: BigNumberish,
      baseOngoingDuration: BigNumberish,
      isOccultistsAttacked: boolean,
      units1: BigNumberish,
      units2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    calculateUserCasualties(
      armyAddress: string,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    canExitFromBattle(overrides?: CallOverrides): Promise<[boolean]>;

    casualties(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    checkCasualties(
      _isSideA: boolean,
      _unitName: string,
      _casualties: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { result: boolean }>;

    exitBattle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLobbyDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getOngoingDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSideALength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSideBLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    initBattle(
      worldAddress: string,
      attackerArmyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isJoinTime(overrides?: CallOverrides): Promise<[boolean]>;

    isOnSideA(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    joinBattle(
      _isSideA: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    offchainCaller(overrides?: CallOverrides): Promise<[string]>;

    position(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number] & {
        continent: BigNumber;
        globalX: number;
        globalY: number;
      }
    >;

    sideA(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    sideB(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    sideUnitsCount(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    startBattle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timing(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        creationTime: BigNumber;
        lobbyDuration: BigNumber;
        ongoingDuration: BigNumber;
        finishTime: BigNumber;
      }
    >;

    userUnitsCount(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    world(overrides?: CallOverrides): Promise<[string]>;
  };

  _calculateAllCasualties(
    overrides?: CallOverrides
  ): Promise<
    [IBattle.CasualtyStructOutput[], IBattle.CasualtyStructOutput[], BigNumber]
  >;

  _calculateStage1CasualtiesForDron(
    overrides?: CallOverrides
  ): Promise<
    [
      IBattle.CasualtyStructOutput[],
      IBattle.CasualtyStructOutput[],
      BigNumber
    ] & {
      _sideACasualties: IBattle.CasualtyStructOutput[];
      _sideBCasualties: IBattle.CasualtyStructOutput[];
      length: BigNumber;
    }
  >;

  assetName(overrides?: CallOverrides): Promise<string>;

  assetType(overrides?: CallOverrides): Promise<string>;

  calculateTimings(
    globalMultiplier: BigNumberish,
    baseLobbyDuration: BigNumberish,
    baseOngoingDuration: BigNumberish,
    isOccultistsAttacked: boolean,
    units1: BigNumberish,
    units2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  calculateUserCasualties(
    armyAddress: string,
    overrides?: CallOverrides
  ): Promise<[string[], BigNumber[]]>;

  canExitFromBattle(overrides?: CallOverrides): Promise<boolean>;

  casualties(
    arg0: boolean,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkCasualties(
    _isSideA: boolean,
    _unitName: string,
    _casualties: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  exitBattle(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLobbyDuration(
    isOccultistsAttacked: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOngoingDuration(
    isOccultistsAttacked: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSideALength(overrides?: CallOverrides): Promise<BigNumber>;

  getSideBLength(overrides?: CallOverrides): Promise<BigNumber>;

  initBattle(
    worldAddress: string,
    attackerArmyAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isJoinTime(overrides?: CallOverrides): Promise<boolean>;

  isOnSideA(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  joinBattle(
    _isSideA: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  offchainCaller(overrides?: CallOverrides): Promise<string>;

  position(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number] & {
      continent: BigNumber;
      globalX: number;
      globalY: number;
    }
  >;

  sideA(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  sideB(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  sideUnitsCount(
    arg0: boolean,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  startBattle(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timing(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      creationTime: BigNumber;
      lobbyDuration: BigNumber;
      ongoingDuration: BigNumber;
      finishTime: BigNumber;
    }
  >;

  userUnitsCount(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  world(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _calculateAllCasualties(
      overrides?: CallOverrides
    ): Promise<
      [
        IBattle.CasualtyStructOutput[],
        IBattle.CasualtyStructOutput[],
        BigNumber
      ]
    >;

    _calculateStage1CasualtiesForDron(
      overrides?: CallOverrides
    ): Promise<
      [
        IBattle.CasualtyStructOutput[],
        IBattle.CasualtyStructOutput[],
        BigNumber
      ] & {
        _sideACasualties: IBattle.CasualtyStructOutput[];
        _sideBCasualties: IBattle.CasualtyStructOutput[];
        length: BigNumber;
      }
    >;

    assetName(overrides?: CallOverrides): Promise<string>;

    assetType(overrides?: CallOverrides): Promise<string>;

    calculateTimings(
      globalMultiplier: BigNumberish,
      baseLobbyDuration: BigNumberish,
      baseOngoingDuration: BigNumberish,
      isOccultistsAttacked: boolean,
      units1: BigNumberish,
      units2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    calculateUserCasualties(
      armyAddress: string,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    canExitFromBattle(overrides?: CallOverrides): Promise<boolean>;

    casualties(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkCasualties(
      _isSideA: boolean,
      _unitName: string,
      _casualties: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    exitBattle(overrides?: CallOverrides): Promise<void>;

    getLobbyDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOngoingDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSideALength(overrides?: CallOverrides): Promise<BigNumber>;

    getSideBLength(overrides?: CallOverrides): Promise<BigNumber>;

    initBattle(
      worldAddress: string,
      attackerArmyAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isJoinTime(overrides?: CallOverrides): Promise<boolean>;

    isOnSideA(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    joinBattle(_isSideA: boolean, overrides?: CallOverrides): Promise<void>;

    offchainCaller(overrides?: CallOverrides): Promise<string>;

    position(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number] & {
        continent: BigNumber;
        globalX: number;
        globalY: number;
      }
    >;

    sideA(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    sideB(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    sideUnitsCount(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    startBattle(overrides?: CallOverrides): Promise<void>;

    timing(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        creationTime: BigNumber;
        lobbyDuration: BigNumber;
        ongoingDuration: BigNumber;
        finishTime: BigNumber;
      }
    >;

    userUnitsCount(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    world(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CasualtiesAdded(bool,uint256,uint256)"(
      isSideA?: boolean | null,
      unitSpec?: BigNumberish | null,
      casualities?: null
    ): CasualtiesAddedEventFilter;
    CasualtiesAdded(
      isSideA?: boolean | null,
      unitSpec?: BigNumberish | null,
      casualities?: null
    ): CasualtiesAddedEventFilter;

    "Finished(uint256,uint256[],uint256[])"(
      finishTime?: null,
      casualitiesA?: null,
      casualitiesB?: null
    ): FinishedEventFilter;
    Finished(
      finishTime?: null,
      casualitiesA?: null,
      casualitiesB?: null
    ): FinishedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Joined(address,bool)"(
      armyAddress?: null,
      isSideA?: null
    ): JoinedEventFilter;
    Joined(armyAddress?: null, isSideA?: null): JoinedEventFilter;
  };

  estimateGas: {
    _calculateAllCasualties(overrides?: CallOverrides): Promise<BigNumber>;

    _calculateStage1CasualtiesForDron(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assetName(overrides?: CallOverrides): Promise<BigNumber>;

    assetType(overrides?: CallOverrides): Promise<BigNumber>;

    calculateTimings(
      globalMultiplier: BigNumberish,
      baseLobbyDuration: BigNumberish,
      baseOngoingDuration: BigNumberish,
      isOccultistsAttacked: boolean,
      units1: BigNumberish,
      units2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateUserCasualties(
      armyAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canExitFromBattle(overrides?: CallOverrides): Promise<BigNumber>;

    casualties(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkCasualties(
      _isSideA: boolean,
      _unitName: string,
      _casualties: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exitBattle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLobbyDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOngoingDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSideALength(overrides?: CallOverrides): Promise<BigNumber>;

    getSideBLength(overrides?: CallOverrides): Promise<BigNumber>;

    initBattle(
      worldAddress: string,
      attackerArmyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isJoinTime(overrides?: CallOverrides): Promise<BigNumber>;

    isOnSideA(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    joinBattle(
      _isSideA: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    offchainCaller(overrides?: CallOverrides): Promise<BigNumber>;

    position(overrides?: CallOverrides): Promise<BigNumber>;

    sideA(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    sideB(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    sideUnitsCount(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    startBattle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timing(overrides?: CallOverrides): Promise<BigNumber>;

    userUnitsCount(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    world(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _calculateAllCasualties(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _calculateStage1CasualtiesForDron(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assetName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateTimings(
      globalMultiplier: BigNumberish,
      baseLobbyDuration: BigNumberish,
      baseOngoingDuration: BigNumberish,
      isOccultistsAttacked: boolean,
      units1: BigNumberish,
      units2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateUserCasualties(
      armyAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canExitFromBattle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    casualties(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkCasualties(
      _isSideA: boolean,
      _unitName: string,
      _casualties: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exitBattle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLobbyDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOngoingDuration(
      isOccultistsAttacked: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSideALength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSideBLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initBattle(
      worldAddress: string,
      attackerArmyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isJoinTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOnSideA(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    joinBattle(
      _isSideA: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    offchainCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    position(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sideA(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sideB(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sideUnitsCount(
      arg0: boolean,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    startBattle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timing(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userUnitsCount(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    world(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
