/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface IContinentInterface extends utils.Interface {
  functions: {
    "calculatePath(uint32[])": FunctionFragment;
    "continentName()": FunctionFragment;
    "continentTileMap(uint32)": FunctionFragment;
    "getCoordinates(uint32)": FunctionFragment;
    "getPosition(uint16,uint16)": FunctionFragment;
    "getTileMovingTime(uint8)": FunctionFragment;
    "getZoneTemplatesLength()": FunctionFragment;
    "getZonesLength()": FunctionFragment;
    "init(address,string)": FunctionFragment;
    "isNeighborTo(uint32,uint32)": FunctionFragment;
    "newAssetSettlement(uint256,uint16,uint16,string)": FunctionFragment;
    "newSettlement(uint16,uint16,uint256,uint256)": FunctionFragment;
    "settlements(uint16,uint16)": FunctionFragment;
    "zoneTemplates(uint256)": FunctionFragment;
    "zones(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "calculatePath"
      | "continentName"
      | "continentTileMap"
      | "getCoordinates"
      | "getPosition"
      | "getTileMovingTime"
      | "getZoneTemplatesLength"
      | "getZonesLength"
      | "init"
      | "isNeighborTo"
      | "newAssetSettlement"
      | "newSettlement"
      | "settlements"
      | "zoneTemplates"
      | "zones"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculatePath",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "continentName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "continentTileMap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCoordinates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTileMovingTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getZoneTemplatesLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getZonesLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isNeighborTo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "newAssetSettlement",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "newSettlement",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlements",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "zoneTemplates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "zones", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "calculatePath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "continentName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "continentTileMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCoordinates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTileMovingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZoneTemplatesLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZonesLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNeighborTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newAssetSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zoneTemplates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zones", data: BytesLike): Result;

  events: {
    "ArmySpawned(address)": EventFragment;
    "NewSettlement(address,string,address,uint16,uint16,uint32)": EventFragment;
    "NewZone(address,uint16[],uint16[],uint16[],uint32[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ArmySpawned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewSettlement"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewZone"): EventFragment;
}

export interface ArmySpawnedEventObject {
  armyAddress: string;
}
export type ArmySpawnedEvent = TypedEvent<[string], ArmySpawnedEventObject>;

export type ArmySpawnedEventFilter = TypedEventFilter<ArmySpawnedEvent>;

export interface NewSettlementEventObject {
  contractAddress: string;
  scriptName: string;
  zoneAddress: string;
  globalX: number;
  globalY: number;
  position: number;
}
export type NewSettlementEvent = TypedEvent<
  [string, string, string, number, number, number],
  NewSettlementEventObject
>;

export type NewSettlementEventFilter = TypedEventFilter<NewSettlementEvent>;

export interface NewZoneEventObject {
  zoneAddress: string;
  coordinatesX: number[];
  coordinatesY: number[];
  tileTypes: number[];
  positions: number[];
}
export type NewZoneEvent = TypedEvent<
  [string, number[], number[], number[], number[]],
  NewZoneEventObject
>;

export type NewZoneEventFilter = TypedEventFilter<NewZoneEvent>;

export interface IContinent extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IContinentInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculatePath(
      path: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & { isValid: boolean; totalPathTime: BigNumber }
    >;

    continentName(overrides?: CallOverrides): Promise<[string]>;

    continentTileMap(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number, number, number, number] & {
        tile0: number;
        tile1: number;
        tile2: number;
        tile3: number;
        tile4: number;
        tile5: number;
        tile6: number;
        tile7: number;
      }
    >;

    getCoordinates(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    getPosition(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getTileMovingTime(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getZoneTemplatesLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getZonesLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    init(
      _worldAddress: string,
      _continentName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isNeighborTo(
      position: BigNumberish,
      neighbor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    newAssetSettlement(
      ownerTokenId: BigNumberish,
      globalX: BigNumberish,
      globalY: BigNumberish,
      assetName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newSettlement(
      globalX: BigNumberish,
      globalY: BigNumberish,
      ownerTokenId: BigNumberish,
      maxBlessTokensToUse: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settlements(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    zoneTemplates(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    zones(index: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  calculatePath(
    path: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber] & { isValid: boolean; totalPathTime: BigNumber }
  >;

  continentName(overrides?: CallOverrides): Promise<string>;

  continentTileMap(
    position: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number, number, number, number, number, number] & {
      tile0: number;
      tile1: number;
      tile2: number;
      tile3: number;
      tile4: number;
      tile5: number;
      tile6: number;
      tile7: number;
    }
  >;

  getCoordinates(
    position: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[number, number]>;

  getPosition(
    x: BigNumberish,
    y: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  getTileMovingTime(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getZoneTemplatesLength(overrides?: CallOverrides): Promise<BigNumber>;

  getZonesLength(overrides?: CallOverrides): Promise<BigNumber>;

  init(
    _worldAddress: string,
    _continentName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isNeighborTo(
    position: BigNumberish,
    neighbor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  newAssetSettlement(
    ownerTokenId: BigNumberish,
    globalX: BigNumberish,
    globalY: BigNumberish,
    assetName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newSettlement(
    globalX: BigNumberish,
    globalY: BigNumberish,
    ownerTokenId: BigNumberish,
    maxBlessTokensToUse: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settlements(
    x: BigNumberish,
    y: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  zoneTemplates(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  zones(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    calculatePath(
      path: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & { isValid: boolean; totalPathTime: BigNumber }
    >;

    continentName(overrides?: CallOverrides): Promise<string>;

    continentTileMap(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number, number, number, number] & {
        tile0: number;
        tile1: number;
        tile2: number;
        tile3: number;
        tile4: number;
        tile5: number;
        tile6: number;
        tile7: number;
      }
    >;

    getCoordinates(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number]>;

    getPosition(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    getTileMovingTime(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZoneTemplatesLength(overrides?: CallOverrides): Promise<BigNumber>;

    getZonesLength(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _worldAddress: string,
      _continentName: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isNeighborTo(
      position: BigNumberish,
      neighbor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    newAssetSettlement(
      ownerTokenId: BigNumberish,
      globalX: BigNumberish,
      globalY: BigNumberish,
      assetName: string,
      overrides?: CallOverrides
    ): Promise<string>;

    newSettlement(
      globalX: BigNumberish,
      globalY: BigNumberish,
      ownerTokenId: BigNumberish,
      maxBlessTokensToUse: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settlements(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    zoneTemplates(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    zones(index: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ArmySpawned(address)"(armyAddress?: null): ArmySpawnedEventFilter;
    ArmySpawned(armyAddress?: null): ArmySpawnedEventFilter;

    "NewSettlement(address,string,address,uint16,uint16,uint32)"(
      contractAddress?: string | null,
      scriptName?: null,
      zoneAddress?: null,
      globalX?: null,
      globalY?: null,
      position?: null
    ): NewSettlementEventFilter;
    NewSettlement(
      contractAddress?: string | null,
      scriptName?: null,
      zoneAddress?: null,
      globalX?: null,
      globalY?: null,
      position?: null
    ): NewSettlementEventFilter;

    "NewZone(address,uint16[],uint16[],uint16[],uint32[])"(
      zoneAddress?: string | null,
      coordinatesX?: null,
      coordinatesY?: null,
      tileTypes?: null,
      positions?: null
    ): NewZoneEventFilter;
    NewZone(
      zoneAddress?: string | null,
      coordinatesX?: null,
      coordinatesY?: null,
      tileTypes?: null,
      positions?: null
    ): NewZoneEventFilter;
  };

  estimateGas: {
    calculatePath(
      path: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    continentName(overrides?: CallOverrides): Promise<BigNumber>;

    continentTileMap(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCoordinates(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPosition(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTileMovingTime(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZoneTemplatesLength(overrides?: CallOverrides): Promise<BigNumber>;

    getZonesLength(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _worldAddress: string,
      _continentName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isNeighborTo(
      position: BigNumberish,
      neighbor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newAssetSettlement(
      ownerTokenId: BigNumberish,
      globalX: BigNumberish,
      globalY: BigNumberish,
      assetName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newSettlement(
      globalX: BigNumberish,
      globalY: BigNumberish,
      ownerTokenId: BigNumberish,
      maxBlessTokensToUse: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settlements(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zoneTemplates(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zones(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    calculatePath(
      path: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    continentName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    continentTileMap(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCoordinates(
      position: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPosition(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTileMovingTime(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getZoneTemplatesLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getZonesLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      _worldAddress: string,
      _continentName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isNeighborTo(
      position: BigNumberish,
      neighbor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newAssetSettlement(
      ownerTokenId: BigNumberish,
      globalX: BigNumberish,
      globalY: BigNumberish,
      assetName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newSettlement(
      globalX: BigNumberish,
      globalY: BigNumberish,
      ownerTokenId: BigNumberish,
      maxBlessTokensToUse: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settlements(
      x: BigNumberish,
      y: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zoneTemplates(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zones(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
