/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBattle,
  IBattleInterface,
} from "../../../../contracts/assets/battles/IBattle";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bool",
        name: "isSideA",
        type: "bool",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "unitSpec",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "casualities",
        type: "uint256",
      },
    ],
    name: "CasualtiesAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "finishTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "casualitiesA",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "casualitiesB",
        type: "uint256[]",
      },
    ],
    name: "Finished",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isSideA",
        type: "bool",
      },
    ],
    name: "Joined",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
    ],
    name: "calculateUserCasualties",
    outputs: [
      {
        internalType: "string[]",
        name: "unitNames",
        type: "string[]",
      },
      {
        internalType: "uint256[]",
        name: "unitsCount",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "canExitFromBattle",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isSideA",
        type: "bool",
      },
      {
        internalType: "string",
        name: "unitName",
        type: "string",
      },
    ],
    name: "casualties",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "exitBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isOccultistsAttacked",
        type: "bool",
      },
    ],
    name: "getLobbyDuration",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isOccultistsAttacked",
        type: "bool",
      },
    ],
    name: "getOngoingDuration",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSideALength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSideBLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_worldAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_creatorArmy",
        type: "address",
      },
    ],
    name: "initBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isJoinTime",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
    ],
    name: "isOnSideA",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_isSideA",
        type: "bool",
      },
    ],
    name: "joinBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "offchainCaller",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "position",
    outputs: [
      {
        internalType: "uint64",
        name: "continent",
        type: "uint64",
      },
      {
        internalType: "uint16",
        name: "globalX",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "globalY",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "sideA",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "sideB",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isSideA",
        type: "bool",
      },
      {
        internalType: "string",
        name: "unitName",
        type: "string",
      },
    ],
    name: "sideUnitsCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "startBattle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "timing",
    outputs: [
      {
        internalType: "uint64",
        name: "creationTime",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "lobbyDuration",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "ongoingDuration",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "finishTime",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "unitName",
        type: "string",
      },
    ],
    name: "userUnitsCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBattle__factory {
  static readonly abi = _abi;
  static createInterface(): IBattleInterface {
    return new utils.Interface(_abi) as IBattleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBattle {
    return new Contract(address, _abi, signerOrProvider) as IBattle;
  }
}
