/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Battle__factory } from "./Battle__factory";
export { BattleFactory__factory } from "./BattleFactory__factory";
export { IBattle__factory } from "./IBattle__factory";
export { IBattleFactory__factory } from "./IBattleFactory__factory";
