/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITaxesFacet, ITaxesFacetInterface } from "../ITaxesFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_taxReceiver",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_punishCountdown",
        type: "uint64",
      },
      {
        internalType: "uint256",
        name: "_punishPercent",
        type: "uint256",
      },
    ],
    name: "taxesFacet_init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_settlementAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "_building",
        type: "string",
      },
    ],
    name: "taxesFacet_claimTax",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_settlementAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "_building",
        type: "string",
      },
    ],
    name: "taxesFacet_canPunish",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_settlementAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "_building",
        type: "string",
      },
    ],
    name: "taxesFacet_punish",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "taxesFacet_data",
    outputs: [
      {
        internalType: "uint256",
        name: "_punishPercent",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_taxReceiver",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_punishCountdown",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITaxesFacet__factory {
  static readonly abi = _abi;
  static createInterface(): ITaxesFacetInterface {
    return new utils.Interface(_abi) as ITaxesFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITaxesFacet {
    return new Contract(address, _abi, signerOrProvider) as ITaxesFacet;
  }
}
