/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUnitsAmm } from "./IUnitsAmm";
export type { IUnitsAmmFactory } from "./IUnitsAmmFactory";
export type { UnitsAmm } from "./UnitsAmm";
export type { UnitsAmmFactory } from "./UnitsAmmFactory";
