/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistry } from "./IRegistry";
export type { IWorld } from "./IWorld";
export type { Registry } from "./Registry";
export type { World } from "./World";
