/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISiege,
  ISiegeInterface,
} from "../../../../contracts/assets/sieges/ISiege";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "unitName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "unitsLiquidated",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "unitsWithdrawn",
        type: "uint256",
      },
    ],
    name: "Liquidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "pointsReceived",
        type: "uint256",
      },
    ],
    name: "PointsReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "pointsSpent",
        type: "uint256",
      },
    ],
    name: "PointsSpent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "settlement",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "unitsNames",
        type: "string[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "unitsCount",
        type: "uint256[]",
      },
    ],
    name: "UnitsAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "settlement",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "unitsNames",
        type: "string[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "unitsCount",
        type: "uint256[]",
      },
    ],
    name: "UnitsWithdrawn",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string[]",
        name: "_unitsNames",
        type: "string[]",
      },
      {
        internalType: "uint256[]",
        name: "_unitsCount",
        type: "uint256[]",
      },
    ],
    name: "addUnits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
    ],
    name: "armyInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "rewardDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "points",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
    ],
    name: "armyLiquidationStartTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "calculateTotalSiegeStats",
    outputs: [
      {
        internalType: "uint256",
        name: "_power",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_supply",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_armyAddress",
        type: "address",
      },
    ],
    name: "canLiquidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "checkLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "buildingAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_points",
        type: "uint256",
      },
    ],
    name: "claimResources",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentSettlement",
    outputs: [
      {
        internalType: "contract ISettlement",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_armyAddress",
        type: "address",
      },
    ],
    name: "getLiquidationUnits",
    outputs: [
      {
        internalType: "uint256[]",
        name: "res",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_armyAddress",
        type: "address",
      },
    ],
    name: "getStoredUnits",
    outputs: [
      {
        internalType: "uint256[]",
        name: "res",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_period",
        type: "uint256",
      },
    ],
    name: "getTotalDamageByPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalDamageLastPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_armyAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "getUserPointsOnTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_worldAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_settlementAddress",
        type: "address",
      },
    ],
    name: "initSiege",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lastUpdate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
    ],
    name: "liquidationPoints",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "spendTime",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pointsPerShare",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "string",
        name: "_unitName",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "returnUnitsToArmy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "armyAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "unitName",
        type: "string",
      },
    ],
    name: "storedUnits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalDamage",
        type: "uint256",
      },
    ],
    name: "systemUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "update",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string[]",
        name: "_unitsNames",
        type: "string[]",
      },
      {
        internalType: "uint256[]",
        name: "_unitsCount",
        type: "uint256[]",
      },
    ],
    name: "withdrawUnits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISiege__factory {
  static readonly abi = _abi;
  static createInterface(): ISiegeInterface {
    return new utils.Interface(_abi) as ISiegeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISiege {
    return new Contract(address, _abi, signerOrProvider) as ISiege;
  }
}
